#!/usr/bin/env bash
rm -rf *.png
rm -rf *.pdf
latex -interaction=nonstopmode Notes.tex
pdflatex -interaction=nonstopmode Notes.tex
dvipng -D 360 -T 6.5in,9.0in Notes.dvi -o display.png
rm -rf *.dvi
rm -rf *.aux
rm -rf *.fdb_latexmk
rm -rf *.fls
rm -rf *.log
